name: CI Express

on: [push, pull_request]

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Installer les dependances
        run: npm ci

      - name: Executer les tests Jest
        run: npm test
